apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: acm-custom-registry
  namespace: openshift-marketplace
spec:
  displayName: Advanced Cluster Management
  publisher: Red Hat
  sourceType: grpc
  image: quay.io/stolostron/acm-custom-registry:2.15.0-SNAPSHOT-2025-07-29-09-51-39
  updateStrategy:
    registryPoll:
      interval: 10m
  secrets:
    - multiclusterhub-operator-pull-secret
