# Copyright Contributors to the Open Cluster Management project
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: multiclusterengine-catalog
  namespace: openshift-marketplace
spec:
  displayName: MultiCluster Engine
  publisher: Red Hat
  sourceType: grpc
  image: quay.io/stolostron/cmb-custom-registry:2.15.0-SNAPSHOT-2025-07-29-09-51-39
  updateStrategy:
    registryPoll:
      interval: 10m
